/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OrganisationRouteImport } from './routes/organisation'
import { Route as OnedriveRouteImport } from './routes/onedrive'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ExtractionRouteImport } from './routes/extraction'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as DetectionRouteImport } from './routes/detection'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as ClassificationRouteImport } from './routes/classification'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationRoute = OrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const OnedriveRoute = OnedriveRouteImport.update({
  id: '/onedrive',
  path: '/onedrive',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionRoute = ExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionRoute = DetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificationRoute = ClassificationRouteImport.update({
  id: '/classification',
  path: '/classification',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classification': typeof ClassificationRoute
  '/configuration': typeof ConfigurationRoute
  '/converter': typeof ConverterRoute
  '/detection': typeof DetectionRoute
  '/drive': typeof DriveRoute
  '/extraction': typeof ExtractionRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/onedrive': typeof OnedriveRoute
  '/organisation': typeof OrganisationRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classification': typeof ClassificationRoute
  '/configuration': typeof ConfigurationRoute
  '/converter': typeof ConverterRoute
  '/detection': typeof DetectionRoute
  '/drive': typeof DriveRoute
  '/extraction': typeof ExtractionRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/onedrive': typeof OnedriveRoute
  '/organisation': typeof OrganisationRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classification': typeof ClassificationRoute
  '/configuration': typeof ConfigurationRoute
  '/converter': typeof ConverterRoute
  '/detection': typeof DetectionRoute
  '/drive': typeof DriveRoute
  '/extraction': typeof ExtractionRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/onedrive': typeof OnedriveRoute
  '/organisation': typeof OrganisationRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/classification'
    | '/configuration'
    | '/converter'
    | '/detection'
    | '/drive'
    | '/extraction'
    | '/health'
    | '/logs'
    | '/onedrive'
    | '/organisation'
    | '/pipeline'
    | '/reports'
    | '/settings'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/classification'
    | '/configuration'
    | '/converter'
    | '/detection'
    | '/drive'
    | '/extraction'
    | '/health'
    | '/logs'
    | '/onedrive'
    | '/organisation'
    | '/pipeline'
    | '/reports'
    | '/settings'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/classification'
    | '/configuration'
    | '/converter'
    | '/detection'
    | '/drive'
    | '/extraction'
    | '/health'
    | '/logs'
    | '/onedrive'
    | '/organisation'
    | '/pipeline'
    | '/reports'
    | '/settings'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClassificationRoute: typeof ClassificationRoute
  ConfigurationRoute: typeof ConfigurationRoute
  ConverterRoute: typeof ConverterRoute
  DetectionRoute: typeof DetectionRoute
  DriveRoute: typeof DriveRoute
  ExtractionRoute: typeof ExtractionRoute
  HealthRoute: typeof HealthRoute
  LogsRoute: typeof LogsRoute
  OnedriveRoute: typeof OnedriveRoute
  OrganisationRoute: typeof OrganisationRoute
  PipelineRoute: typeof PipelineRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation': {
      id: '/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof OrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onedrive': {
      id: '/onedrive'
      path: '/onedrive'
      fullPath: '/onedrive'
      preLoaderRoute: typeof OnedriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extraction': {
      id: '/extraction'
      path: '/extraction'
      fullPath: '/extraction'
      preLoaderRoute: typeof ExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classification': {
      id: '/classification'
      path: '/classification'
      fullPath: '/classification'
      preLoaderRoute: typeof ClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClassificationRoute: ClassificationRoute,
  ConfigurationRoute: ConfigurationRoute,
  ConverterRoute: ConverterRoute,
  DetectionRoute: DetectionRoute,
  DriveRoute: DriveRoute,
  ExtractionRoute: ExtractionRoute,
  HealthRoute: HealthRoute,
  LogsRoute: LogsRoute,
  OnedriveRoute: OnedriveRoute,
  OrganisationRoute: OrganisationRoute,
  PipelineRoute: PipelineRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
